cmdargs:
  severity: style_problem

  color: true

  env:
    neovim: true

policies:
  ProhibitMissingScriptEncoding:
    enabled: false

  ProhibitUsingUndeclaredVariable:
    enabled: false

  ProhibitSetNoCompatible:
    enabled: false

  ProhibitImplicitScopeVariable:
    enabled: false

