[colors.bright]
black = "0x002b36"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"

[colors.cursor]
cursor = "0x839496"
text = "0x002b36"

[colors.normal]
black = "0x073642"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[colors.primary]
background = "0x002b36"
foreground = "0x839496"

[font]
size = 13

[font.italic]
family = "JuliaMono"
style = "RegularItalic"

[font.normal]
family = "JuliaMono"
style = "Regular"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_padding = true

[window.dimensions]
columns = 82
lines = 51

[window.padding]
x = 0
y = 0
