$print_type = 'pdf';
$pdf_mode = 1;
$pdf_previewer = 'start okular';
push @generated_exts, "spl";
push @generated_exts, "nav";
push @generated_exts, "snm";
push @generated_exts, "tdo";
push @generated_exts, "nmo";
push @generated_exts, "synctex.gz";
push @generated_exts, "tex.latexmain";
$latex = 'latex --src-specials %O %S';
$pdflatex = 'pdflatex -synctex=1 -interaction=nonstopmode --shell-escape %O %S';
$succom='sleep 3; xdotool search --class okular set_window --name "Compile OK"';
$failcom='sleep 3; xdotool search --class okular set_window --name "Compile FAILED"';
$compcom='xdotool search --class okular set_window --name "Compiling"';
