[settings]
dotfiles.root = "~/.dotfiles"
dotfiles.default_mode = "symlink"

[bootstrap.repos]
"~/.config/nvim" = { url = "git@github.com:lervag/dotnvim.git", ref = "main" }
"~/.password-store" = { url = "git@github.com:lervag/pass", ref = "master" }
"~/scripts" = { url = "git@github.com:lervag/scripts.git", ref = "master" }

# third-party additions
"~/.zsh/zsh-completions" = { url = "https://github.com/zsh-users/zsh-completions.git", ref = "master" }
"~/.zsh/zsh-syntax-highlighting" = { url = "https://github.com/zsh-users/zsh-syntax-highlighting.git", ref = "master" }

[dotfiles]
"~/.Xresources" = {}
"~/.bash_profile" = {}
"~/.bashrc" = {}
"~/.chktexrc" = {}
"~/.claude/keybindings.json" = {}
"~/.claude/settings.json" = {}
"~/.clisprc.lisp" = {}
"~/.config/ack/ackrc" = {}
"~/.config/alacritty" = { mode = "symlink-each" }
"~/.config/alsa/asoundrc" = {}
"~/.config/apy/apy.json" = {}
"~/.config/bat/config" = {}
"~/.config/conky" = { mode = "symlink-each" }
"~/.config/dunst/dunstrc" = {}
"~/.config/feh/themes" = {}
"~/.config/flameshot/flameshot.ini" = {}
"~/.config/git/config" = {}
"~/.config/git/config-thermophys" = {}
"~/.config/git/ignore" = {}
"~/.config/hg/hgrc" = {}
"~/.config/kitty" = { mode = "symlink-each" }
"~/.config/latexmk/latexmkrc" = {}
"~/.config/mise/config.toml" = ".mise.global.config"
"~/.config/ncspot/config.toml" = {}
"~/.config/npm/npmrc" = {}
"~/.config/sioyek" = { mode = "symlink-each" }
"~/.config/starship.toml" = {}
"~/.config/stylua/stylua.toml" = {}
"~/.config/systemd/user/check-battery.service" = {}
"~/.config/systemd/user/check-battery.timer" = {}
"~/.config/tmuxinator" = { mode = "symlink-each" }
"~/.config/tridactyl/tridactylrc" = {}
"~/.config/wezterm" = { mode = "symlink-each" }
"~/.config/workmux/config.yaml" = {}
"~/.config/zathura/zathurarc" = {}
"~/.config/zellij/config.kdl" = {}
"~/.dircolors.ansi-dark" = {}
"~/.fluxbox" = { mode = "symlink-each" }
"~/.gnome-keybidings" = {}
"~/.gnupg/gpg-agent.conf" = {}
"~/.gtkrc-2.0.mine" = {}
"~/.hgk" = {}
"~/.inputrc" = {}
"~/.irbrc" = {}
"~/.lisp-common" = {}
"~/.local/bin/dots" = {}
"~/.mailrc" = {}
"~/.pam_environment" = {}
"~/.pdfpcrc" = {}
"~/.pg_format" = {}
"~/.profile" = {}
"~/.pylintrc" = {}
"~/.pythonrc.py" = {}
"~/.references-mine.bib" = {}
"~/.references.bib" = {}
"~/.sbclrc" = {}
"~/.screenrc" = {}
"~/.ssh/config" = {}
"~/.texmf" = { mode = "symlink-each" }
"~/.tmux.conf" = {}
"~/.toprc" = {}
"~/.vim" = { mode = "symlink-each" }
"~/.vintrc.yaml" = {}
"~/.xinitrc" = {}
"~/.xprofile" = {}
"~/.zshenv" = {}
"~/.zshrc" = {}
