#!/bin/bash

xcompmgr &
dunst &>/tmp/dunst.log &

# Source environment variables
source /home/lervag/.profile

exec fluxbox \
  -no-slit -no-toolbar \
  -log "/home/lervag/.fluxbox/log" &
fbpid=$!

sleep 0.5

# Source local init file, if any
local=/home/lervag/.fluxbox.startup.local
[ -f "$local" ] && source "$local"

conky &

# Ensure that the Xorg session has a valid keyboard layout
setxkbmap \
  -model pc105 \
  -layout no \
  -variant nodeadkeys \
  -option ctrl:nocaps \
  -option compose:rctrl

wait $fbpid
