#!/bin/bash

xcompmgr &
dropbox &
dunst &
xfce4-power-manager &
set-keyboard.sh

# Source environment variables
source /home/lervag/.dotfiles/profile

exec fluxbox \
  -no-slit -no-toolbar \
  -log "/home/lervag/.fluxbox/log" &
fbpid=$!

sleep 0.5

# Source local init file, if any
local=/home/lervag/.fluxbox.startup.local
[ -f "$local" ] && source "$local"

{
  conky -c /home/lervag/.dotfiles/conky_workspaces &
  conky -c /home/lervag/.dotfiles/conky_system &
} &

wait $fbpid
